<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>

<body>
    <script>
        function doSomething() {
            return new Promise((resolve, reject) => {
                const rnd = 500 + Math.random() * 1000;
                setTimeout(function () {
                    resolve(rnd)
                }, rnd)
            });
        }

        // 同一個scope內要用不同名稱
        // async await為非同步
        async function a() {
            const r1 = await doSomething()
            console.log(r1)
            const r2 = await doSomething()
            console.log(r2)
            console.log(await doSomething())
        }

        a().then(r => {
            console.log('end', r)
        });

        // async await抓取錯誤時, 使用try catch, finally無論是否有錯誤皆會執行
        (async () => {
            try {
                for (let i = 1; i < 10; i++) {
                    console.log(i, await doSomething())
                }
            } catch (ex) {

            } finally {

            }
        })()


    </script>


</body>

</html>